In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({'text':['campusx watch campusx','people watch campusx','people write comments','campusx write comments'],'output':[1,1,0,0]})

In [3]:
df

text  output
0   campusx watch campusx       1
1    people watch campusx       1
2   people write comments       0
3  campusx write comments       0

## Bag Of Words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
cv.vocabulary_

{'campusx': 0, 'watch': 3, 'people': 2, 'write': 4, 'comments': 1}

In [9]:
bow[0].toarray()

array([[2, 0, 0, 1, 0]], dtype=int64)

In [12]:
cv.transform(['campusx write and watch comment of people and people']).toarray()

array([[1, 0, 2, 1, 1]], dtype=int64)

## Baf Of N-Grams

In [13]:
cv = CountVectorizer(ngram_range=(2,2))               ### bigram ---> for trigram use (3,3) and so on

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
cv.vocabulary_

{'campusx watch': 0,
 'watch campusx': 4,
 'people watch': 2,
 'people write': 3,
 'write comments': 5,
 'campusx write': 1}

In [16]:
bow[0].toarray()

array([[1, 0, 0, 0, 1, 0]], dtype=int64)

## TF - IDF 

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
tfidf = TfidfVectorizer()

In [20]:
bow = tfidf.fit_transform(df['text'])

In [23]:
bow.toarray()

array([[0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [25]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comments' 'people' 'watch' 'write']
